internalName: myv_ru-win

locales:
  en:
    name: &bundleName "Erzya Mordvin Keyboards"
    description: "Mobile OS keyboards for the Erzya Mordvin language from the Divvun group at UiT."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [myv-mob, myv-mac, myv-win]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.myv
    icon: images/myv-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard
    version: "1.0.0"
    build: "1"

  ios: &AppleID
    codeSignId: "2K5J2584NX"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.myv
    bundleName: *bundleName
    icon: images/myv-icon.png
    version: "1.0.0"
    build: "1"

  osx:
    <<: *AppleID
    icon: images/myv-keyboard-menu-icon.png
    resources: doc
    version: "1.0.1"
    build: "1"

  win:
    appName: *bundleName
    url: "http://divvun.no"
    uuid: "BF2342BD-688E-4AC8-890A-F8F57FB54265"
    version: "1.0.1"
    build: "1"
