locales:
  en:
    name: Erzya Mordvin Keyboards
    description: >-
      Mobile OS keyboards for the Erzya Mordvin language from the Divvun group
      at UiT.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
